<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "globale"
 *
 * Auto generated by Extension Builder 2020-06-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Referenzen',
    'description' => 'GSG Referenzen',
    'category' => 'plugin',
    'author' => 'Aydin Mirzaghayev',
    'author_email' => 'aydin.mirzaghayev@gmx.de',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
